# Change these first
owner: mooseburgr # Your GitHub organization or username, where this repository lives
repo: plex-upptime # The name of this repository

sites:
  - name: kmj.wtf
    url: https://kmj.wtf
  - name: plex server
    url: $PLEX_URL
    __dangerous__insecure: true
    icon: https://app.plex.tv/desktop/favicon.ico

status-website:
  baseUrl: /plex-upptime
  theme: dark
  logoUrl: https://avatars.githubusercontent.com/u/5505573
  name: kmj.wtf upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/mooseburgr/plex-upptime

user-agent: mooseburgr

assignees:
  - mooseburgr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
